DATABASE = 'mangrove_web'
SERVER = 'http://localhost:5984'
COUCHDB_USERNAME = 'admin'
COUCHDB_PASSWORD = 'admin'
COUCHDB_CREDENTIALS = (COUCHDB_USERNAME,COUCHDB_PASSWORD)
CACHE_SERVERS = ["127.0.0.1"]

